#!/usr/bin/env node
// Rewrites the block between the engine's CALIBRATION markers with the measured tables.
// v3 (spec D1/D3): three duration anchors. The generated block carries CAL_ANCHORS plus
// EMPTY-SHAPED BASELINE/BUFF_V; the hand-written interpolation code that lives directly
// after the END marker fills them via setEncounterDuration(). The shapes matter: every
// buff key must pre-exist so PARTY_BUFFS' `BUFF_V['X'] || {}` captures a live object, not
// an orphan literal. No loader change and no build step.
import { readFileSync, writeFileSync } from 'node:fs';

const here = p => new URL(p, import.meta.url);
const enginePath = here('../assignments-engine.js');
const engine = readFileSync(enginePath, 'utf8');

const DURATIONS = [200, 300, 520];
const anchors = {};
for (const d of DURATIONS) {
    anchors[d] = JSON.parse(readFileSync(here(`./weights-${d}.json`), 'utf8'));
}

const START = /\/\/ === CALIBRATION START[^\n]*\n/;
const END = '// === CALIBRATION END ===';
const startMatch = engine.match(START);
const startIdx = engine.search(START);
const endIdx = engine.indexOf(END);
if (startIdx === -1 || endIdx === -1) throw new Error('calibration markers not found');

// Every row name the engine's PARTY_BUFFS table references must exist IN EVERY anchor, or
// interpolation would silently rate a real buff worthless at some durations. Baseline spec
// sets must match across anchors for the same reason — interpolation walks one anchor's keys.
const required = [...engine.matchAll(/BUFF_V\['([^']+)'\]/g)].map(m => m[1]);
const allBuffNames = new Set(required);
const allSpecKeys = new Set();
for (const d of DURATIONS) {
    Object.keys(anchors[d].buffs).forEach(b => allBuffNames.add(b));
    Object.keys(anchors[d].baselines).forEach(k => allSpecKeys.add(k));
}
for (const d of DURATIONS) {
    for (const b of allBuffNames) anchors[d].buffs[b] = anchors[d].buffs[b] || {};
    for (const k of allSpecKeys) {
        if (anchors[d].baselines[k] == null) {
            throw new Error(`weights-${d}.json is missing baseline ${k} — anchors must cover identical spec sets`);
        }
    }
}

const indent = obj => JSON.stringify(obj, null, 8).replace(/\n/g, '\n    ');
const markerLine = '    // === CALIBRATION START (generated — do not hand-edit; regenerate with calibration/inject-weights.mjs) ===\n';
const provenance = DURATIONS.map(d =>
    `    //   ${d}s: wowsims ${anchors[d].meta.wowsimsSha}, ${anchors[d].meta.encounter}, ` +
    `${anchors[d].meta.iterations} iterations, ${anchors[d].meta.date}.`).join('\n');
const buffShape = {};
for (const b of allBuffNames) buffShape[b] = {};
const anchorsOut = Object.fromEntries(DURATIONS.map(d =>
    [d, { baselines: anchors[d].baselines, buffs: anchors[d].buffs }]));
const block =
    `    // Generated by calibration/inject-weights.mjs from calibration/weights-{${DURATIONS.join(',')}}.json.\n` +
    provenance + '\n' +
    `    // Values below the ${anchors[DURATIONS[0]].meta.noiseFloor} noise floor are recorded as absent, not as small.\n` +
    `    // BASELINE and BUFF_V start EMPTY-SHAPED: setEncounterDuration() (hand-written,\n` +
    `    // directly after the END marker) fills them by interpolating CAL_ANCHORS, mutating\n` +
    `    // in place so the references PARTY_BUFFS captures stay live.\n` +
    `    // DO NOT HAND-EDIT — see calibration/README.md for the caveats these numbers carry.\n` +
    `    const CAL_ANCHORS = ${indent(anchorsOut)};\n` +
    `    const BASELINE = {};\n` +
    `    const BUFF_V = ${indent(buffShape)};\n    `;

writeFileSync(enginePath, engine.slice(0, startIdx - 4) + markerLine + block + engine.slice(endIdx));
console.log('engine calibration block rewritten with anchors ' + DURATIONS.join('/'));
