#!/usr/bin/env node
// Rewrites the block between the engine's CALIBRATION markers with the measured tables.
// No loader change and no build step: the engine stays one UMD file that node and the
// browser both read directly.
import { readFileSync, writeFileSync } from 'node:fs';

const here = p => new URL(p, import.meta.url);
const enginePath = here('../assignments-engine.js');
const weights = JSON.parse(readFileSync(here('./weights.json'), 'utf8'));
const engine = readFileSync(enginePath, 'utf8');

const START = /\/\/ === CALIBRATION START[^\n]*\n/;
const END = '// === CALIBRATION END ===';
const startMatch = engine.match(START);
const startIdx = engine.search(START);
const endIdx = engine.indexOf(END);
if (startIdx === -1 || endIdx === -1) throw new Error('calibration markers not found');

// Every row name the engine's PARTY_BUFFS table references must exist as a key, or the
// table's `BUFF_V['X'] || {}` would silently degrade a real buff to worthless.
const required = [...engine.matchAll(/BUFF_V\['([^']+)'\]/g)].map(m => m[1]);
const missing = [...new Set(required)].filter(k => !(k in weights.buffs));
if (missing.length) {
    console.error('weights.json has no entry for: ' + missing.join(', '));
    console.error('Adding them as empty so the lookup never misses — check whether that is right.');
    missing.forEach(k => { weights.buffs[k] = {}; });
}

const indent = obj => JSON.stringify(obj, null, 8).replace(/\n/g, '\n    ');
// Rewrite the marker line itself: after the first injection it no longer holds "provisional
// hand values", and a stale header is exactly the kind of thing that gets believed later.
const markerLine = '    // === CALIBRATION START (generated — do not hand-edit; regenerate with calibration/inject-weights.mjs) ===\n';
const headerEnd = startIdx + startMatch[0].length;
const block =
    `    // Generated by calibration/inject-weights.mjs from calibration/weights.json.\n` +
    `    // Provenance: wowsims ${weights.meta.wowsimsSha}, ${weights.meta.encounter}, ` +
    `${weights.meta.iterations} iterations, ${weights.meta.date}.\n` +
    `    // Values below the ${weights.meta.noiseFloor} noise floor are recorded as absent, not as small.\n` +
    `    // DO NOT HAND-EDIT — see calibration/README.md for the caveats these numbers carry.\n` +
    `    const BASELINE = ${indent(weights.baselines)};\n` +
    `    const BUFF_V = ${indent(weights.buffs)};\n    `;

writeFileSync(enginePath, engine.slice(0, startIdx - 4) + markerLine + block + engine.slice(endIdx));
console.log('engine calibration block rewritten');
