(function (root, factory) {
    if (typeof module === 'object' && module.exports) module.exports = factory(require('./tactics-bloodboil-steps.js'), require('./tactics-mother-steps.js'), require('./tactics-council-steps.js'), require('./tactics-illidan-steps.js'), require('./tactics-hyjal-steps.js'));
    else root.TacticsSteps = factory(root.TacticsBloodboilSteps, root.TacticsMotherSteps, root.TacticsCouncilSteps, root.TacticsIllidanSteps, root.TacticsHyjalSteps);
}(typeof self !== 'undefined' ? self : this, function (BLOODBOIL, MOTHER, COUNCIL, ILLIDAN, HYJAL) {
    'use strict';
    const step = (id, title, detail, startMs, holdAtMs, options = {}) => ({ id, title, detail, startMs, holdAtMs, tip: options.tip || '', optional: !!options.optional, countdownSeconds: options.countdownSeconds || 0, loop: options.loop || 'hold' });
    const beats = (duration, rows) => rows.map(([startMs, id, title, detail, options], localIndex) => step(id, title, detail, startMs, localIndex + 1 < rows.length ? rows[localIndex + 1][0] - 1 : duration, options));
    const staticBeat = (title, detail) => [step('the-plan', title, detail, 0, 0)];
    function define(chapters) {
        const order = Object.keys(chapters);
        const allSteps = order.flatMap(sceneId => chapters[sceneId].map((item, localIndex) => ({ ...item, sceneId, chapterId: sceneId, localIndex, count: chapters[sceneId].length, sampleMs: item.startMs, range: [item.startMs, item.holdAtMs] }))).map((item, index) => ({ ...item, index }));
        const byId = new Map(allSteps.map(item => [item.sceneId + ':' + item.id, item]));
        const forScene = sceneId => allSteps.filter(item => item.sceneId === sceneId);
        const indexFor = (sceneId, sourceTimeMs) => {
            const candidates = allSteps.filter(item => item.sceneId === sceneId);
            const containing = candidates.filter(item => item.startMs <= sourceTimeMs && sourceTimeMs <= item.holdAtMs);
            const pool = containing.length ? containing : candidates.filter(item => item.startMs <= sourceTimeMs);
            const selected = pool.reduce((chosen, item) => item.startMs >= chosen.startMs ? item : chosen, pool[0]);
            return selected ? allSteps.indexOf(selected) : -1;
        };
        return { order, forScene, all: () => allSteps, get: (sceneId, id) => byId.get(sceneId + ':' + id) || null,
            frameAt: (item, elapsedMs) => Math.min(item.holdAtMs, item.startMs + Math.max(0, elapsedMs)),
            countdownAt: (item, elapsedMs) => item.countdownSeconds ? Math.max(0, Math.ceil((item.countdownSeconds * 1000 - elapsedMs) / 1000)) : null,
            indexFor, timelineFor(sceneId, sourceTimeMs) { const index = indexFor(sceneId, sourceTimeMs), item = allSteps[index]; if (!item) return null; return { index, localIndex: item.localIndex, elapsedMs: Math.max(0, Math.min(item.holdAtMs, sourceTimeMs) - item.startMs), sourceTimeMs: Math.min(item.holdAtMs, sourceTimeMs), sampleMs: item.startMs, range: [item.startMs, item.holdAtMs], step: item }; },
            chapterBoundary(sceneId, localIndex) { const chapterIndex = order.indexOf(sceneId), nextSceneId = order[chapterIndex + (localIndex < 0 ? -1 : 1)]; if (!nextSceneId) return null; const chapter = forScene(nextSceneId); return { sceneId: nextSceneId, localIndex: localIndex < 0 ? Math.max(0, chapter.length - 1) : 0 }; }
        };
    }
    const sup = {
        overview: staticBeat('Two phases. Two different jobs.', 'Damage in Phase 1. Survival in Phase 2. Prepare for each threat reset.'),
        'p1-stand': staticBeat('Start with tank control and a loose spread.', 'Tanks establish control, then the raid uses the first damage window.'),
        'p1-hateful': beats(8000, [[0,'mt-swing','Main tank takes the normal swing.','Keep the boss faced away while the Hateful tank builds threat.'],[2600,'prepare-soak','Prepare the Hateful soak.','Keep the eligible high-threat soak healthy before the strike.'],[3200,'hateful-hit','Hateful hits the prepared soak.','Keep the eligible high-threat soak healthy.'],[4000,'recover-soak','Restore the soak.','Healers recover the Hateful tank before the next strike.'],[6200,'next-hateful','The next Hateful strike lands.','The soak remains in melee, high on threat and health.']]),
        'p1-flame': beats(22000, [[0,'punch-tell','Molten Punch signals the fire.','Watch the tell and leave an open route.'],[1000,'move-out','Move sideways out of blue fire.','The targeted player crosses into clear ground.'],[11000,'chase-stops','The chase stops; the trail remains.','Do not step back onto the burning path.'],[21000,'trail-clears','The trail is clear.','Resume from safe ground.']]),
        swap: beats(8000, [[0,'make-space','Melee makes space before Phase 2.','Tanks keep tanking until fixate begins.'],[5000,'phase-two','Threat resets: watch the first fixate.','Clear the selected player’s route.']]),
        'p2-fixate': beats(20000, [[0,'first-target','The first target runs.','Everyone clears the route and healers move with the raid.'],[10000,'next-target','The target changes.','Read the new route instead of following a fixed circuit.']]),
        'p2-geyser': beats(12000, [[0,'spread-ready','Keep the spread ready.','Open ground gives nearby players somewhere to move.'],[1000,'first-geyser','First volcano: move nearby players.','Leave a margin beyond the illustrative danger ring.'],[3500,'second-geyser','Another volcano appears.','Each nearby player moves; this is not a one-player mechanic.'],[6000,'third-geyser','Check every eruption before choosing ground.','Stay in healing reach while moving.']]),
        'p2-together': beats(20000, [[0,'read-both','Read target and ground together.','The runner needs an open route.'],[1500,'first-volcano','A volcano changes the available route.','Nearby players leave it immediately.'],[8500,'second-volcano','Another eruption overlaps the route.','Change direction if the ground ahead is unsafe.'],[10000,'next-fixate','The target changes again.','Keep the new runner in healing reach.']]),
        back: beats(15000, [[0,'ease-off','Ease off before the reset.','Tanks prepare within reach.'],[5000,'pickup','Threat reset: tanks pick up.','Misdirect supports the pickup when available.'],[8500,'reposition','Tank control: melee returns.','Reposition only after control is established.']])
    };
    const naj = {
        overview: staticBeat('One fight, repeated shield interruptions.', 'Spread, rescue, heal, make one called throw, then recover.'),
        positioning: staticBeat('One tank, room for everyone else.', 'Keep healers in reach and leave practical space for Needle splash.'),
        needle: beats(9000, [[0,'spread','Give Needle targets room.','Starting space reduces splash exposure.'],[1000,'needle-hit','Needle hits its selected targets.','Heal the hit and avoid clustering beside a target.'],[2601,'recover-needle','Recover the splash.','Resume your job with practical spacing.']]),
        impale: beats(10000, [[0,'watch','Watch for the Impaling Spine.','A free nearby player is ready to respond.'],[1000,'pinned','An ally is pinned.','The victim calls their location.'],[2000,'rescue','A free player reaches the spine.','The rescuer clicks it; the victim cannot free themself.'],[4500,'keep-spine','Keep the collected spine.','It is saved for the shield call.']]),
        shield: beats(9000, [[0,'shield-up','Tidal Shield is up.','Damage pauses into immunity.'],[4500,'raid-ready','The raid is topped and ready.','Adequate buffed maximum health is required for the 8,500 Frost burst; the holder still waits for the throw call.']]),
        burst: beats(11000, [[0,'shield-window','Use the shield window.','Top the whole raid before a throw.'],[3500,'ready-call','The raid is ready for one throw.','Other holders keep their spare spines.'],[5000,'throw','One holder throws the spine.','Throw within range only on the call.'],[5700,'burst-hit','Tidal Burst hits everyone.','Recover the simultaneous Frost hit.'],[6700,'recover','Recover together.','Healthstones can help after the burst.']]),
        cycle: beats(76000, [[0,'opening','Keep the rescue rhythm.','Spread and watch for the first Needle.'],[8000,'needle-one','Needle: give targets room.','Heal splash damage and keep spacing.'],[9601,'needle-reset','Needle recovery is complete.','Keep spacing for the next rescue.'],[20000,'impale-one','First Impale: free the ally.','The rescuer keeps the spine.'],[24000,'spine-one','The first spine is collected.','Save it for the shield call.'],[32000,'needle-two','Needle returns.','Maintain room and healing coverage.'],[40000,'impale-two','Second Impale: free the ally.','This creates the spare spine.'],[44000,'spine-two','Keep the spare spine.','The primary holder still waits for the call.'],[48001,'spare-ready','The spare spine is ready.','Keep it for the next shield.'],[60000,'shield','Tidal Shield pauses damage.','Top the raid before the break.'],[65000,'ready','The raid is ready.','One holder prepares to throw.'],[67000,'throw','One called throw breaks the shield.','Other holders keep their spare.'],[67700,'burst','Tidal Burst lands raidwide.','Recover the whole raid together.'],[68700,'recovery','Recovery is underway.','Reset for the next shield.']])
    };
    const aka = {
        overview: staticBeat('Free the Shade. Save Akama.', 'Kill channels, control the doors, then burn the Shade.'),
        positioning: staticBeat('Set both hallways before talking to Akama.', 'Tanks take the doors, healers know their tank, and damage starts on Channelers.'),
        channelers: beats(14000, [[0,'binding','Six Channelers bind the Shade.','Damage stays on the objective.'],[4000,'progress','Channelers are falling.','Each kill removes a binding beam.'],[12000,'binding-clear','The last beam disappears.','Tanks still control incoming adds.']]),
        doorways: beats(11000, [[0,'doors-ready','Hallway teams are ready.','Tanks protect healers while damage stays on Channelers.'],[1000,'waves','The first hallway wave arrives.','Catch it before it reaches healers.'],[4500,'hold','Tanks hold the wave.','Use the prepared lane and slows when available.'],[5500,'interrupt','Stop the Spiritbinder heal.','Do not let it restore Channeler progress.'],[7301,'control','The interrupt window has passed.','Keep the wave controlled and damage on Channelers.']]),
        sorcerers: beats(11000, [[0,'watch','Watch for a reinforcing Sorcerer.','The binding objective remains the priority.'],[1000,'spawn','A Sorcerer enters.','Damage switches to the reinforcement.'],[4000,'renewed-binding','The Sorcerer renews the binding.','Kill it before it stalls release.'],[8000,'sorcerer-dead','The reinforcement is down.','Finish the remaining Channeler.'],[10000,'binding-clear','The binding is clear.','Prepare for the Shade’s walk.']]),
        fire: beats(9000, [[0,'clear-ground','Keep clear ground available.','Everyone keeps tank coverage in mind.'],[1500,'rain','Rain of Fire appears.','Affected players leave the orange area.'],[3700,'move-clear','Players move clear.','The fire remains on its original ground.'],[7500,'return','Return to your job from safe ground.','Do not stand in fire for another cast.']]),
        walk: beats(16000, [[0,'walk-start','The Shade begins to walk.','Tanks bring controlled packs with it.'],[5000,'rendezvous','Bring packs beside the moving Shade.','Healers travel with their assigned tanks.'],[7000,'cleanup','Use the walk for cleanup.','Damage clears adds after the group meets.'],[14000,'engage','Akama engages the Shade.','Lust is saved for this damage race.']]),
        burn: beats(14000, [[0,'engaged','Akama holds the Shade.','Player tanks retain any surviving adds.'],[12000,'complete','The Shade is defeated.','No active jobs remain.']]),
        cycle: beats(42000, [[0,'start','Start on the Channelers.','Hallway control supports the objective.'],[3000,'waves','The hallway wave arrives.','Tanks catch it while damage kills channels.'],[6500,'channel-progress','Channeler progress continues.','Keep interrupts and tank healing covered.'],[9000,'fire','Rain of Fire demands movement.','Leave it without abandoning your job.'],[16000,'walk','The Shade begins the walk.','Bring controlled packs along.'],[19000,'rendezvous','Meet the moving Shade.','Healers keep tank packs covered.'],[21000,'cleanup','Clean up the gathered adds.','Save Lust for engagement.'],[28000,'engage','Akama engages the Shade.','Damage swaps to the burn.'],[40000,'complete','The Shade is defeated.','No active jobs remain.']]),
        aoe: beats(38500, [[0,'optional-plan','Optional: stack at the Channelers.','This route needs reliable tank healing and interrupts.',{optional:true}],[3000,'pull','Bring waves to the Channelers.','Tanks keep the stacked pack controlled.',{optional:true}],[6000,'stack','The wave reaches the Channelers.','Keep the Channelers as the active target.',{optional:true}],[6500,'aoe','AoE channels and adds together.','Switch to the Shade after release.',{optional:true}],[12500,'release','The binding releases.','Tanks retain the survivors.',{optional:true}],[24500,'engage','Akama engages the Shade.','Damage starts the burn.',{optional:true}],[36500,'complete','The Shade is defeated.','No active jobs remain.',{optional:true}]])
    };
    const r = {
        overview: staticBeat('Three essences. One controlled sequence.', 'Suffering, souls, Desire, souls, then Anger: each essence changes the raid job.'), positioning: staticBeat('Use the sheet formation before the pull.', 'Tanks in front, melee behind, ranged split wide and healers central enough to cover both sides.'),
        fixate: [step('hold-fixates','Keep the same tank while healthy.','Fixate checks who is closest every five seconds. Swap when health, shields or cooldowns call for it.',0,10999),step('low-health','Tank health is getting low.','Prepare a fresh tank before it is unsafe, then hand off at the next Fixate.',11000,13999),step('incoming-tank','Next tank in; current tank out.','The fresh tank becomes closest for the next check.',14000,14999),step('first-handoff','Fresh tank has Fixate.','The previous tank keeps its lost health while the fresh tank holds closest.',15000,16999)],
        suffering: [step('suffering-rule','No healing or mana regeneration.','Armor is removed and defense is reduced by 500 while Suffering is active.',0,900),step('soul-drain','Soul Drain arrives.','It drains health and mana. Magic dispel takes priority.',1000,2900),step('dispel-drain','Dispel Soul Drain first.','Remove the magic debuff before other dispels.',3000,4900),step('priest-shield','Priest shield still works.','Absorbs protect the current tank even though healing cannot.',5000,6900),step('healer-dps','Healers DPS during Suffering.','Healing and mana regeneration remain disabled.',7000,8999),step('enrage-prep','Prepare cooldowns for Enrage.','Around 0:45, Enrage lasts 15 seconds. Prepare a tank with cooldowns and avoidance.',9000,11999),step('enrage-survival','Use cooldowns to survive Enrage.','Use cooldowns and avoidance; hold the prepared tank while safe.',12000,17999),step('rogue-evasion','Optional: Rogue Evasion.','A Rogue can use Evasion as an optional Enrage survival reminder.',14900,14900,{optional:true,loop:'effect'}),step('hunter-deterrence','Optional: Hunter Deterrence.','A Hunter can use Deterrence as an optional Enrage survival reminder.',15100,16900,{optional:true,loop:'effect'})],
        souls: [step('gather-souls','Gather ghosts at the raid.','Bring souls to the group. Do not kill them across the room.',1000,4000),step('kill-soul','Kill the gathered soul.','Only souls killed at the raid restore health and mana.',5000,5400),step('soul-recovery','Soul recovery reaches the raid.','Health and mana return together after the nearby death.',5500,6499)],
        desire: [step('desire-damage','Damage starts the recoil.','Fifty percent of damage returns to its attacker.',2000,2290),step('desire-recoil','Recoil returns to the attacker.','The same player takes the return damage.',2300,2890),step('desire-heal','Healing recovers the recoil.','Healing is doubled during Aura of Desire.',2900,3800),step('mana-depletion','Maximum mana shrinks toward zero.','This accelerated demonstration reaches the real-fight 2:40 zero-mana point; preserve priority casts.',0,14000)],
        interrupts: [step('tongues','Curse of Tongues stays up.','The Warlock makes the one-second Spirit Shock cast 1.6 seconds for a bigger kick window.',0,1190,{loop:'effect'}),step('first-spirit-shock','The assigned player interrupts Spirit Shock.','Use the assigned kick. A missed Shock incapacitates the tank and swaps threat.',2000,4200),step('rune-shield','Rune Shield blocks interrupts.','Remove Rune Shield before kicking. Mage Spellsteal is preferred; purge or dispel is fallback.',5000,6900),step('spellsteal','Remove Rune Shield.','After Spellsteal or the eligible fallback removal, the next interrupt can land.',7000,7900),step('next-spirit-shock','The next assigned player interrupts Spirit Shock.','Keep Curse of Tongues up and continue the assigned kick rotation.',8000,9999)],
        deaden: [step('deaden-cast','Deaden doubles incoming damage.','The assigned interrupter stops the cast.',3000,3990),step('deaden-kick','Use the normal assigned Deaden kick.','The normal interrupt is the plan.',4000,4990),step('spell-reflection','Optional: Protection Warrior Spell Reflection.','A coordinated Spell Reflection is an optional alternative that makes the boss take doubled damage.',5000,7490,{optional:true}),step('deadly-throw','Optional: Rogue Deadly Throw backup.','Rogue arena gloves can add an interrupt backup; they are not required for the rotation.',7500,9999,{optional:true})],
        anger: [step('anger-preparation','Prepare Shadow Protection.','Use Shadow Protection before Anger and keep the front clear for Soul Scream.',0,1900),step('anger-pickup','The off-tank picks up Anger.','The raid waits while the off-tank establishes the first pickup.',0,1900),step('anger-taunt','The main tank taunts at 0:02.','Seethe is a tank survival cue. Wait four more seconds before raid damage.',2000,5900),step('anger-burn','Threat is set: raid burns.','Start damage and available Bloodlust at 0:06. Keep Soul Scream frontal clear.',6000,13900),step('soul-scream','Spend rage before Soul Scream.','Soul Scream burns rage for extra damage. Spend it first; paladins spend mana. Face Anger away.',10000,17999)],
        spite: [step('spite-countdown','Spite marks: prepare for impact.','Marked players are immune for six seconds. Heal them before the Nature impact.',3000,9000,{countdownSeconds:6}),step('spite-impact','Spite impacts for about 7500 Nature damage.','The immunity ends once; the impact lands and the marked players need recovery.',9000,10799),step('spite-recovery','Recover after Spite.','Healers recover marked players while damage continues.',10800,11500),step('spite-healthstone','Use a healthstone after Spite.','Healthstones are an optional personal recovery reminder after the impact.',10800,11999,{optional:true})],
        cycle: beats(100000, [[0,'suffering-hold','Hold Suffering while safe.','The current tank stays closest until a health-based handoff is needed.'],[11000,'low-health','Prepare the fresh tank.','Move the fresh tank closest for the next needed Fixate.'],[14000,'incoming-tank','The fresh tank moves closest.','The current tank moves out before the next Fixate.'],[15000,'first-handoff','The Fixate handoff happens.','The new tank now holds closest.'],[16000,'enrage-prep','Prepare survival tools for Enrage.','Hold the prepared tank while safe.'],[17000,'enrage-survival','Enrage: use prepared survival tools.','Hold the prepared tank through Enrage.'],[20000,'souls-one','Gather souls for recovery.','Kill them at the raid.'],[32000,'desire','Desire reflects damage.','Heal recoil and preserve mana.'],[40000,'tongues','Keep Tongues up.','Prepare the shield-removal and kick chain.'],[42000,'first-shock','The assigned player interrupts Spirit Shock.','A missed kick swaps threat.'],[45000,'rune-shield','Rune Shield blocks the kick.','Remove it before interrupting.'],[47000,'remove-shield','Remove Rune Shield.','The next kick can then land.'],[48000,'next-shock','The next Spirit Shock is casting.','The assigned player interrupts it before the cast completes.'],[49600,'next-kick','The next Spirit Shock is interrupted.','Continue the assigned rotation.'],[50000,'deaden-ready','Prepare for Deaden.','The normal assigned kick remains the plan.'],[53000,'deaden-cast','Deaden doubles incoming damage.','The assigned interrupter stops the cast.'],[54000,'deaden-kick','Use the normal assigned Deaden kick.','The normal interrupt is the plan.'],[55000,'deaden','Optional Deaden tools are visible.','The normal assigned kick remains the plan.',{optional:true}],[57500,'deaden-backup','Optional backup remains optional.','Do not replace the normal rotation.',{optional:true}],[60000,'souls-two','Recover after Desire.','Gather and kill souls at the group.'],[72000,'anger-pickup','Secure Anger first.','Off-tank pickup comes before raid damage.'],[74000,'anger-taunt','Main tank taunts at 0:02.','Wait four more seconds before damage.'],[78000,'anger-burn','Threat is set: raid burns.','Start damage and available Bloodlust.'],[86000,'scream','Keep Soul Scream frontal clear.','Spend tank resources before it lands.'],[88000,'spite-marks','Spite marks are immune.','Top them before the Nature impact.'],[94000,'spite-impact','Spite impacts.','Recover marked players.'],[95800,'recovery','Recovery finishes the Anger window.','Keep pressure on the boss.'],[99000,'complete','Reliquary defeated.','No active jobs remain.']])
    };
    const registries = {'bt-supremus':define(sup),'bt-najentus':define(naj),'bt-akama':define(aka),'bt-reliquary':define(r),'bt-bloodboil':define(BLOODBOIL),'bt-mother':define(MOTHER),'bt-council':define(COUNCIL),'bt-illidan':define(ILLIDAN)};
    Object.entries(HYJAL).forEach(([fightId, chapters]) => { registries[fightId] = define(chapters); });
    return { forFight: fight => registries[fight] || define({}), fights: Object.keys(registries) };
}));
