const assert = require('node:assert/strict');
const Lesson = require('./tactics-lesson-render.js');
const ctx = { font: '', measureText: value => ({ width: String(value).length * 8 }) };
const lesson = { title: 'A deliberately long lesson title that must remain inside the instruction panel', detail: 'This detail is intentionally long enough to wrap onto several measured lines without obscuring the playable map.', tip: 'Keep the danger warning visible while each role has a concrete job.', rows: [['Tanks with a very long assignment', 'Keep the boss stable and make room for the incoming player.'], ['Healers', 'Keep both assigned targets covered during movement.'], ['Damage', 'Use the safe lane and stop on the call.']], warning: 'Do not run through the group while the hazard is active.', recap: false };
const layout = Lesson.layout(ctx, 420, 720, lesson);
assert.ok(layout.action.h >= 0, 'reserved lesson panels leave a non-negative action rectangle');
assert.ok(layout.header.titleLines.length > 1, 'long title wraps inside the measured header');
assert.ok(layout.footer.rows.every(row => row.jobLines.length > 0), 'role jobs are measured into visible footer lines');
assert.ok(layout.footer.rows.every(row => row.jobLines.every(line => ctx.measureText(line).width <= 372)), 'wrapped role lines fit their rendered footer width');
assert.ok(layout.footer.y >= layout.action.y + layout.action.h, 'footer starts after the action rectangle');
const longHeader = Lesson.layout(ctx, 420, 720, { ...lesson, rows: [['Tanks', 'Hold.']], warning: '', title: lesson.title + ' with another measured line', detail: lesson.detail + ' and a second detailed sentence.' });
const longFooter = Lesson.layout(ctx, 420, 720, { ...lesson, title: 'Short call', detail: 'Short detail.', tip: '', rows: lesson.rows.concat([['Raid', 'Stay spread and recover together before moving back into the assigned lane.']]), warning: lesson.warning + ' Keep every player clear until the caller confirms recovery.' });
const reserved = Lesson.reserve([longHeader, longFooter], 420, 720);
assert.equal(reserved.header.h, longHeader.header.h, 'reservation keeps the tallest header even when another explanation has the tallest footer');
assert.equal(reserved.footer.h, longFooter.footer.h, 'reservation keeps the tallest footer independently');
assert.equal(reserved.action.y, reserved.header.y + reserved.header.h + 8, 'reserved action begins below the shared header');
assert.equal(reserved.footer.y, reserved.action.y + reserved.action.h + 8, 'reserved action ends before the shared footer');
const Reliquary = require('./tactics-reliquary-render.js');
const relApi = { ctx, width: 420, height: 900 };
const relHeader = Reliquary.layout(relApi, {}, { teaching: { title: lesson.title, detail: lesson.detail } });
const relFooter = Reliquary.layout(relApi, {}, { teaching: { title: 'Hold.', detail: 'Wait.', tip: lesson.detail + ' ' + lesson.warning } });
const relReserved = Reliquary.reserve([relHeader, relFooter], 420, 900);
assert.equal(relReserved.header.h, relHeader.header.h, 'Reliquary reserves its tallest explanation independently');
assert.equal(relReserved.footer.h, relFooter.footer.h, 'Reliquary reserves its longest tip independently');
assert.ok(relReserved.clip.y >= relReserved.header.y + relReserved.header.h, 'actor clip excludes the explanation panel');
assert.ok(relReserved.clip.y + relReserved.clip.h <= relReserved.footer.y, 'actor clip excludes the footer');
assert.ok(relReserved.action.y - relReserved.clip.y >= 30, 'camera leaves clipping room for tank health bars');
console.log('lesson layout checks passed');
